version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-ecr: circleci/aws-ecr@6.7.0
  
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  
workflows:
    build-and-test:
      jobs:
        - build-and-test
    build_and_push_image:
      jobs:
        - aws-ecr/build-and-push-image:
            account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
            aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
            aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
            context: aws
            create-repo: true
            dockerfile: Dockerfile
            region: AWS_REGION_ENV_VAR_NAME
            repo: koa_docker_demo
            tag: 'latest,myTag'